### ISSUE TITLE
LMS200 calibration information?

### ISSUE THREAD

**Issue by zkytony** [carlosmccosta/dynamic_robot_localization_dissertation#1]
Hi Carlos,

I'm a fellow robotics researcher at the University of Washington.

It looks like you have experience working with the LMS200 laser scanner when writing this dissertation, and it looks like you collected some bag files in which there is scan messages generated from the LMS200 laser scanner. Do you have a bag file that can share with me?

I am currently converting some old scan data (6 years old), in csv format to rosbag, and these scans are collected using LMS200 scanner. I would like to know what's the correct value to set for time_increment and scan_time for the laser messages. So I wonder that it may be easier to know if I can see those messages from a bag directly recorded using LMS200.

I really appreciate your time.

**Comment by carlosmccosta** [comment]
Good afternoon :)

The bag files i used that contained the LMS200 sensor data are from this dataset:
http://vision.in.tum.de/data/datasets/rgbd-dataset

This dataset contains 4 tests with a pionner robot with the sick lidar mounted on top.
You can download them from "Robot SLAM" section in:
http://vision.in.tum.de/data/datasets/rgbd-dataset/download

If you prefer the bag files with just the lidar data and ground truth you can download them from my robot localization tests repository.
https://github.com/carlosmccosta/dynamic_robot_localization_tests#pioneer-in-industrial-hall
https://github.com/carlosmccosta/dynamic_robot_localization_tests/tree/hydro-devel/datasets/tum

In these bag files, this was the configuration of the LaserScan message:
http://docs.ros.org/api/sensor_msgs/html/msg/LaserScan.html

angle_min: -1.57079637051
angle_max: 1.57079637051
angle_increment: 0.0174532923847
time_increment: 3.70370362361e-05
scan_time: 0.0133333336562
range_min: 0.0
range_max: 81.0
ranges: [...] (181 measurements)
intensities: []


These values are close to the official specifications of the lidar (page 29):
http://sicktoolbox.sourceforge.net/docs/sick-lms-technical-description.pdf

Given that this laser was configured with a angular resolution of 1 degree and it can operate up to 75 Hz:

scan_time -> 0.01333 seconds (75 Hz)

Assuming no lag between the end of one scan and start of another, the time between measurements would be:
time_increment -> 1 / 75 / 181 = 0.000073665 seconds

So, according to the configuration of the bag files, the dataset authors considered that there was a lag of:
1 / 75 - 0.000037037 × 180 = 0.006666673 seconds


Have a nice day :)

**Comment by zkytony** [comment]
Thank you so much for this information! I believe this will also help others who were googling for the correct parameters of LMS200 :) :+1: 

Good luck on your current pursuits!
